INSERT INTO "library_app_userprofile_friends" ("id", "from_userprofile_id", "to_userprofile_id") VALUES(9,1,2);
INSERT INTO "library_app_userprofile_friends" ("id", "from_userprofile_id", "to_userprofile_id") VALUES(10,2,1);
INSERT INTO "library_app_userprofile_friends" ("id", "from_userprofile_id", "to_userprofile_id") VALUES(13,3,2);
INSERT INTO "library_app_userprofile_friends" ("id", "from_userprofile_id", "to_userprofile_id") VALUES(14,2,3);
INSERT INTO "library_app_userprofile_friends" ("id", "from_userprofile_id", "to_userprofile_id") VALUES(15,3,1);
INSERT INTO "library_app_userprofile_friends" ("id", "from_userprofile_id", "to_userprofile_id") VALUES(16,1,3);
INSERT INTO "library_app_userprofile_friends" ("id", "from_userprofile_id", "to_userprofile_id") VALUES(17,5,2);
INSERT INTO "library_app_userprofile_friends" ("id", "from_userprofile_id", "to_userprofile_id") VALUES(18,2,5);
